// src/components/ChemistryLab/chemistryData.js

// Periodic Table Data
export const periodicTableData = [
  // Row 1
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: 1.008,
    category: "nonmetal",
    electronegativity: 2.2,
    electronConfiguration: "1s1",
    density: 0.0000899,
    meltingPoint: 14.01,
    boilingPoint: 20.28,
    discoveredBy: "Henry Cavendish",
    discoveryYear: 1766,
    xpos: 1,
    ypos: 1
  },
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    atomicMass: 4.0026,
    category: "noble gas",
    electronegativity: null,
    electronConfiguration: "1s2",
    density: 0.0001785,
    meltingPoint: 0.95,
    boilingPoint: 4.22,
    discoveredBy: "Pierre Janssen, Norman Lockyer",
    discoveryYear: 1868,
    xpos: 18,
    ypos: 1
  },
  
  // Row 2
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: 6.94,
    category: "alkali metal",
    electronegativity: 0.98,
    electronConfiguration: "[He] 2s1",
    density: 0.534,
    meltingPoint: 453.69,
    boilingPoint: 1560,
    discoveredBy: "Johan August Arfwedson",
    discoveryYear: 1817,
    xpos: 1,
    ypos: 2
  },
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicMass: 9.0122,
    category: "alkaline earth metal",
    electronegativity: 1.57,
    electronConfiguration: "[He] 2s2",
    density: 1.85,
    meltingPoint: 1560,
    boilingPoint: 2742,
    discoveredBy: "Louis Nicolas Vauquelin",
    discoveryYear: 1798,
    xpos: 2,
    ypos: 2
  },
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    atomicMass: 10.81,
    category: "metalloid",
    electronegativity: 2.04,
    electronConfiguration: "[He] 2s2 2p1",
    density: 2.34,
    meltingPoint: 2349,
    boilingPoint: 4200,
    discoveredBy: "Joseph Louis Gay-Lussac, Louis Jacques Thénard",
    discoveryYear: 1808,
    xpos: 13,
    ypos: 2
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: 12.011,
    category: "nonmetal",
    electronegativity: 2.55,
    electronConfiguration: "[He] 2s2 2p2",
    density: 2.267,
    meltingPoint: 3823,
    boilingPoint: 4300,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 14,
    ypos: 2
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: 14.007,
    category: "nonmetal",
    electronegativity: 3.04,
    electronConfiguration: "[He] 2s2 2p3",
    density: 0.001251,
    meltingPoint: 63.15,
    boilingPoint: 77.36,
    discoveredBy: "Daniel Rutherford",
    discoveryYear: 1772,
    xpos: 15,
    ypos: 2
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: 15.999,
    category: "nonmetal",
    electronegativity: 3.44,
    electronConfiguration: "[He] 2s2 2p4",
    density: 0.001429,
    meltingPoint: 54.36,
    boilingPoint: 90.20,
    discoveredBy: "Carl Wilhelm Scheele",
    discoveryYear: 1771,
    xpos: 16,
    ypos: 2
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: 18.998,
    category: "halogen",
    electronegativity: 3.98,
    electronConfiguration: "[He] 2s2 2p5",
    density: 0.001696,
    meltingPoint: 53.53,
    boilingPoint: 85.03,
    discoveredBy: "André-Marie Ampère",
    discoveryYear: 1810,
    xpos: 17,
    ypos: 2
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    atomicMass: 20.180,
    category: "noble gas",
    electronegativity: null,
    electronConfiguration: "[He] 2s2 2p6",
    density: 0.0008999,
    meltingPoint: 24.56,
    boilingPoint: 27.07,
    discoveredBy: "William Ramsay, Morris Travers",
    discoveryYear: 1898,
    xpos: 18,
    ypos: 2
  },
  
  // Row 3
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: 22.990,
    category: "alkali metal",
    electronegativity: 0.93,
    electronConfiguration: "[Ne] 3s1",
    density: 0.971,
    meltingPoint: 370.87,
    boilingPoint: 1156,
    discoveredBy: "Humphry Davy",
    discoveryYear: 1807,
    xpos: 1,
    ypos: 3
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: 24.305,
    category: "alkaline earth metal",
    electronegativity: 1.31,
    electronConfiguration: "[Ne] 3s2",
    density: 1.738,
    meltingPoint: 923,
    boilingPoint: 1363,
    discoveredBy: "Joseph Black",
    discoveryYear: 1755,
    xpos: 2,
    ypos: 3
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminum",
    atomicMass: 26.982,
    category: "post-transition metal",
    electronegativity: 1.61,
    electronConfiguration: "[Ne] 3s2 3p1",
    density: 2.698,
    meltingPoint: 933.47,
    boilingPoint: 2792,
    discoveredBy: "Hans Christian Ørsted",
    discoveryYear: 1825,
    xpos: 13,
    ypos: 3
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: 28.085,
    category: "metalloid",
    electronegativity: 1.9,
    electronConfiguration: "[Ne] 3s2 3p2",
    density: 2.3296,
    meltingPoint: 1687,
    boilingPoint: 3538,
    discoveredBy: "Jöns Jacob Berzelius",
    discoveryYear: 1824,
    xpos: 14,
    ypos: 3
  },
  {
    atomicNumber: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicMass: 30.974,
    category: "nonmetal",
    electronegativity: 2.19,
    electronConfiguration: "[Ne] 3s2 3p3",
    density: 1.82,
    meltingPoint: 317.3,
    boilingPoint: 550,
    discoveredBy: "Hennig Brand",
    discoveryYear: 1669,
    xpos: 15,
    ypos: 3
  },
  {
    atomicNumber: 16,
    symbol: "S",
    name: "Sulfur",
    atomicMass: 32.06,
    category: "nonmetal",
    electronegativity: 2.58,
    electronConfiguration: "[Ne] 3s2 3p4",
    density: 2.067,
    meltingPoint: 388.36,
    boilingPoint: 717.87,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 16,
    ypos: 3
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: 35.45,
    category: "halogen",
    electronegativity: 3.16,
    electronConfiguration: "[Ne] 3s2 3p5",
    density: 0.003214,
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    discoveredBy: "Carl Wilhelm Scheele",
    discoveryYear: 1774,
    xpos: 17,
    ypos: 3
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    atomicMass: 39.948,
    category: "noble gas",
    electronegativity: null,
    electronConfiguration: "[Ne] 3s2 3p6",
    density: 0.0017837,
    meltingPoint: 83.80,
    boilingPoint: 87.30,
    discoveredBy: "Lord Rayleigh, William Ramsay",
    discoveryYear: 1894,
    xpos: 18,
    ypos: 3
  },
  
  // Row 4 (first part)
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    atomicMass: 39.098,
    category: "alkali metal",
    electronegativity: 0.82,
    electronConfiguration: "[Ar] 4s1",
    density: 0.862,
    meltingPoint: 336.53,
    boilingPoint: 1032,
    discoveredBy: "Humphry Davy",
    discoveryYear: 1807,
    xpos: 1,
    ypos: 4
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicMass: 40.078,
    category: "alkaline earth metal",
    electronegativity: 1.00,
    electronConfiguration: "[Ar] 4s2",
    density: 1.54,
    meltingPoint: 1115,
    boilingPoint: 1757,
    discoveredBy: "Humphry Davy",
    discoveryYear: 1808,
    xpos: 2,
    ypos: 4
  },
  
  // Transition metals row 4
  {
    atomicNumber: 21,
    symbol: "Sc",
    name: "Scandium",
    atomicMass: 44.956,
    category: "transition metal",
    electronegativity: 1.36,
    electronConfiguration: "[Ar] 3d1 4s2",
    density: 2.985,
    meltingPoint: 1814,
    boilingPoint: 3109,
    discoveredBy: "Lars Fredrik Nilson",
    discoveryYear: 1879,
    xpos: 3,
    ypos: 4
  },
  {
    atomicNumber: 22,
    symbol: "Ti",
    name: "Titanium",
    atomicMass: 47.867,
    category: "transition metal",
    electronegativity: 1.54,
    electronConfiguration: "[Ar] 3d2 4s2",
    density: 4.507,
    meltingPoint: 1941,
    boilingPoint: 3560,
    discoveredBy: "William Gregor",
    discoveryYear: 1791,
    xpos: 4,
    ypos: 4
  },
  {
    atomicNumber: 23,
    symbol: "V",
    name: "Vanadium",
    atomicMass: 50.942,
    category: "transition metal",
    electronegativity: 1.63,
    electronConfiguration: "[Ar] 3d3 4s2",
    density: 6.11,
    meltingPoint: 2183,
    boilingPoint: 3680,
    discoveredBy: "Andrés Manuel del Río",
    discoveryYear: 1801,
    xpos: 5,
    ypos: 4
  },
  {
    atomicNumber: 24,
    symbol: "Cr",
    name: "Chromium",
    atomicMass: 51.996,
    category: "transition metal",
    electronegativity: 1.66,
    electronConfiguration: "[Ar] 3d5 4s1",
    density: 7.15,
    meltingPoint: 2180,
    boilingPoint: 2944,
    discoveredBy: "Louis Nicolas Vauquelin",
    discoveryYear: 1794,
    xpos: 6,
    ypos: 4
  },
  {
    atomicNumber: 25,
    symbol: "Mn",
    name: "Manganese",
    atomicMass: 54.938,
    category: "transition metal",
    electronegativity: 1.55,
    electronConfiguration: "[Ar] 3d5 4s2",
    density: 7.21,
    meltingPoint: 1519,
    boilingPoint: 2334,
    discoveredBy: "Johann Gottlieb Gahn",
    discoveryYear: 1774,
    xpos: 7,
    ypos: 4
  },
  {
    atomicNumber: 26,
    symbol: "Fe",
    name: "Iron",
    atomicMass: 55.845,
    category: "transition metal",
    electronegativity: 1.83,
    electronConfiguration: "[Ar] 3d6 4s2",
    density: 7.874,
    meltingPoint: 1811,
    boilingPoint: 3134,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 8,
    ypos: 4
  },
  {
    atomicNumber: 27,
    symbol: "Co",
    name: "Cobalt",
    atomicMass: 58.933,
    category: "transition metal",
    electronegativity: 1.88,
    electronConfiguration: "[Ar] 3d7 4s2",
    density: 8.90,
    meltingPoint: 1768,
    boilingPoint: 3200,
    discoveredBy: "Georg Brandt",
    discoveryYear: 1735,
    xpos: 9,
    ypos: 4
  },
  {
    atomicNumber: 28,
    symbol: "Ni",
    name: "Nickel",
    atomicMass: 58.693,
    category: "transition metal",
    electronegativity: 1.91,
    electronConfiguration: "[Ar] 3d8 4s2",
    density: 8.908,
    meltingPoint: 1728,
    boilingPoint: 3186,
    discoveredBy: "Axel Fredrik Cronstedt",
    discoveryYear: 1751,
    xpos: 10,
    ypos: 4
  },
  {
    atomicNumber: 29,
    symbol: "Cu",
    name: "Copper",
    atomicMass: 63.546,
    category: "transition metal",
    electronegativity: 1.90,
    electronConfiguration: "[Ar] 3d10 4s1",
    density: 8.96,
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 11,
    ypos: 4
  },
  {
    atomicNumber: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicMass: 65.38,
    category: "transition metal",
    electronegativity: 1.65,
    electronConfiguration: "[Ar] 3d10 4s2",
    density: 7.134,
    meltingPoint: 692.68,
    boilingPoint: 1180,
    discoveredBy: "Indian metallurgists",
    discoveryYear: 1000,
    xpos: 12,
    ypos: 4
  },
  
  // Rest of row 4
  {
    atomicNumber: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicMass: 69.723,
    category: "post-transition metal",
    electronegativity: 1.81,
    electronConfiguration: "[Ar] 3d10 4s2 4p1",
    density: 5.91,
    meltingPoint: 302.9146,
    boilingPoint: 2673,
    discoveredBy: "Lecoq de Boisbaudran",
    discoveryYear: 1875,
    xpos: 13,
    ypos: 4
  },
  {
    atomicNumber: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicMass: 72.630,
    category: "metalloid",
    electronegativity: 2.01,
    electronConfiguration: "[Ar] 3d10 4s2 4p2",
    density: 5.323,
    meltingPoint: 1211.40,
    boilingPoint: 3106,
    discoveredBy: "Clemens Winkler",
    discoveryYear: 1886,
    xpos: 14,
    ypos: 4
  },
  {
    atomicNumber: 33,
    symbol: "As",
    name: "Arsenic",
    atomicMass: 74.922,
    category: "metalloid",
    electronegativity: 2.18,
    electronConfiguration: "[Ar] 3d10 4s2 4p3",
    density: 5.727,
    meltingPoint: 1090,
    boilingPoint: 887,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 15,
    ypos: 4
  },
  {
    atomicNumber: 34,
    symbol: "Se",
    name: "Selenium",
    atomicMass: 78.971,
    category: "nonmetal",
    electronegativity: 2.55,
    electronConfiguration: "[Ar] 3d10 4s2 4p4",
    density: 4.81,
    meltingPoint: 494,
    boilingPoint: 958,
    discoveredBy: "Jöns Jacob Berzelius",
    discoveryYear: 1817,
    xpos: 16,
    ypos: 4
  },
  {
    atomicNumber: 35,
    symbol: "Br",
    name: "Bromine",
    atomicMass: 79.904,
    category: "halogen",
    electronegativity: 2.96,
    electronConfiguration: "[Ar] 3d10 4s2 4p5",
    density: 3.1028,
    meltingPoint: 265.8,
    boilingPoint: 332.0,
    discoveredBy: "Antoine Jérôme Balard",
    discoveryYear: 1826,
    xpos: 17,
    ypos: 4
  },
  {
    atomicNumber: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicMass: 83.798,
    category: "noble gas",
    electronegativity: 3.00,
    electronConfiguration: "[Ar] 3d10 4s2 4p6",
    density: 0.003733,
    meltingPoint: 115.79,
    boilingPoint: 119.93,
    discoveredBy: "William Ramsay, Morris Travers",
    discoveryYear: 1898,
    xpos: 18,
    ypos: 4
  },
  
  // Selected lanthanides
  {
    atomicNumber: 57,
    symbol: "La",
    name: "Lanthanum",
    atomicMass: 138.91,
    category: "lanthanide",
    electronegativity: 1.1,
    electronConfiguration: "[Xe] 5d1 6s2",
    density: 6.162,
    meltingPoint: 1193,
    boilingPoint: 3737,
    discoveredBy: "Carl Gustaf Mosander",
    discoveryYear: 1839,
    xpos: 3,
    ypos: 9
  },
  {
    atomicNumber: 58,
    symbol: "Ce",
    name: "Cerium",
    atomicMass: 140.12,
    category: "lanthanide",
    electronegativity: 1.12,
    electronConfiguration: "[Xe] 4f1 5d1 6s2",
    density: 6.770,
    meltingPoint: 1068,
    boilingPoint: 3716,
    discoveredBy: "Martin Heinrich Klaproth, Jöns Jakob Berzelius, Wilhelm Hisinger",
    discoveryYear: 1803,
    xpos: 4,
    ypos: 9
  },
  {
    atomicNumber: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomicMass: 140.91,
    category: "lanthanide",
    electronegativity: 1.13,
    electronConfiguration: "[Xe] 4f3 6s2",
    density: 6.77,
    meltingPoint: 1208,
    boilingPoint: 3793,
    discoveredBy: "Carl Auer von Welsbach",
    discoveryYear: 1885,
    xpos: 5,
    ypos: 9
  },
  {
    atomicNumber: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomicMass: 144.24,
    category: "lanthanide",
    electronegativity: 1.14,
    electronConfiguration: "[Xe] 4f4 6s2",
    density: 7.01,
    meltingPoint: 1297,
    boilingPoint: 3347,
    discoveredBy: "Carl Auer von Welsbach",
    discoveryYear: 1885,
    xpos: 6,
    ypos: 9
  },
  {
    atomicNumber: 62,
    symbol: "Sm",
    name: "Samarium",
    atomicMass: 150.36,
    category: "lanthanide",
    electronegativity: 1.17,
    electronConfiguration: "[Xe] 4f6 6s2",
    density: 7.52,
    meltingPoint: 1345,
    boilingPoint: 2067,
    discoveredBy: "Paul Émile Lecoq de Boisbaudran",
    discoveryYear: 1879,
    xpos: 8,
    ypos: 9
  },
  {
    atomicNumber: 63,
    symbol: "Eu",
    name: "Europium",
    atomicMass: 151.96,
    category: "lanthanide",
    electronegativity: 1.2,
    electronConfiguration: "[Xe] 4f7 6s2",
    density: 5.264,
    meltingPoint: 1099,
    boilingPoint: 1802,
    discoveredBy: "Eugène-Anatole Demarçay",
    discoveryYear: 1901,
    xpos: 9,
    ypos: 9
  },
  {
    atomicNumber: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomicMass: 157.25,
    category: "lanthanide",
    electronegativity: 1.2,
    electronConfiguration: "[Xe] 4f7 5d1 6s2",
    density: 7.90,
    meltingPoint: 1585,
    boilingPoint: 3546,
    discoveredBy: "Jean Charles Galissard de Marignac",
    discoveryYear: 1880,
    xpos: 10,
    ypos: 9
  },
  
  // Selected actinides
  {
    atomicNumber: 89,
    symbol: "Ac",
    name: "Actinium",
    atomicMass: 227.0,
    category: "actinide",
    electronegativity: 1.1,
    electronConfiguration: "[Rn] 6d1 7s2",
    density: 10.07,
    meltingPoint: 1323,
    boilingPoint: 3471,
    discoveredBy: "André-Louis Debierne, Friedrich Oskar Giesel",
    discoveryYear: 1899,
    xpos: 3,
    ypos: 10
  },
  {
    atomicNumber: 90,
    symbol: "Th",
    name: "Thorium",
    atomicMass: 232.04,
    category: "actinide",
    electronegativity: 1.3,
    electronConfiguration: "[Rn] 6d2 7s2",
    density: 11.72,
    meltingPoint: 2115,
    boilingPoint: 5061,
    discoveredBy: "Jöns Jakob Berzelius",
    discoveryYear: 1829,
    xpos: 4,
    ypos: 10
  },
  {
    atomicNumber: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomicMass: 231.04,
    category: "actinide",
    electronegativity: 1.5,
    electronConfiguration: "[Rn] 5f2 6d1 7s2",
    density: 15.37,
    meltingPoint: 1841,
    boilingPoint: 4300,
    discoveredBy: "William Crookes",
    discoveryYear: 1913,
    xpos: 5,
    ypos: 10
  },
  {
    atomicNumber: 93,
    symbol: "Np",
    name: "Neptunium",
    atomicMass: 237.0,
    category: "actinide",
    electronegativity: 1.36,
    electronConfiguration: "[Rn] 5f4 6d1 7s2",
    density: 20.45,
    meltingPoint: 917,
    boilingPoint: 4273,
    discoveredBy: "Edwin McMillan, Philip Abelson",
    discoveryYear: 1940,
    xpos: 5,
    ypos: 10
  },
  
  // Recently discovered or interesting elements
  {
    atomicNumber: 95,
    symbol: "Am",
    name: "Americium",
    atomicMass: 243.0,
    category: "actinide",
    electronegativity: 1.13,
    electronConfiguration: "[Rn] 5f7 7s2",
    density: 13.69,
    meltingPoint: 1449,
    boilingPoint: 2880,
    discoveredBy: "Glenn T. Seaborg",
    discoveryYear: 1944,
    xpos: 7,
    ypos: 10
  },
  {
    atomicNumber: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomicMass: 267.0,
    category: "transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d2 7s2",
    density: 23.2,
    meltingPoint: 2400,
    boilingPoint: 5800,
    discoveredBy: "Joint Institute for Nuclear Research, Lawrence Berkeley National Laboratory",
    discoveryYear: 1964,
    xpos: 4,
    ypos: 7
  },
  {
    atomicNumber: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomicMass: 278.0,
    category: "transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d7 7s2",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "GSI Helmholtz Centre for Heavy Ion Research",
    discoveryYear: 1982,
    xpos: 9,
    ypos: 7
  },
  {
    atomicNumber: 118,
    symbol: "Og",
    name: "Oganesson",
    atomicMass: 294.0,
    category: "noble gas",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d10 7s2 7p6",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Joint Institute for Nuclear Research, Lawrence Livermore National Laboratory",
    discoveryYear: 2002,
    xpos: 18,
    ypos: 7
  }
];