// src/components/ChemistryLab/chemistryData.js

// Complete Periodic Table Data (all 118 elements)
export const periodicTableData = [
  // Period 1
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: 1.008,
    category: "nonmetal",
    electronegativity: 2.2,
    electronConfiguration: "1s1",
    density: 0.0000899,
    meltingPoint: 14.01,
    boilingPoint: 20.28,
    discoveredBy: "Henry Cavendish",
    discoveryYear: 1766,
    xpos: 1,
    ypos: 1
  },
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    atomicMass: 4.0026,
    category: "noble gas",
    electronegativity: null,
    electronConfiguration: "1s2",
    density: 0.0001785,
    meltingPoint: 0.95,
    boilingPoint: 4.22,
    discoveredBy: "Pierre Janssen, Norman Lockyer",
    discoveryYear: 1868,
    xpos: 18,
    ypos: 1
  },
  
  // Period 2
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: 6.94,
    category: "alkali metal",
    electronegativity: 0.98,
    electronConfiguration: "[He] 2s1",
    density: 0.534,
    meltingPoint: 453.69,
    boilingPoint: 1560,
    discoveredBy: "Johan August Arfwedson",
    discoveryYear: 1817,
    xpos: 1,
    ypos: 2
  },
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicMass: 9.0122,
    category: "alkaline earth metal",
    electronegativity: 1.57,
    electronConfiguration: "[He] 2s2",
    density: 1.85,
    meltingPoint: 1560,
    boilingPoint: 2742,
    discoveredBy: "Louis Nicolas Vauquelin",
    discoveryYear: 1798,
    xpos: 2,
    ypos: 2
  },
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    atomicMass: 10.81,
    category: "metalloid",
    electronegativity: 2.04,
    electronConfiguration: "[He] 2s2 2p1",
    density: 2.34,
    meltingPoint: 2349,
    boilingPoint: 4200,
    discoveredBy: "Joseph Louis Gay-Lussac, Louis Jacques Thénard",
    discoveryYear: 1808,
    xpos: 13,
    ypos: 2
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: 12.011,
    category: "nonmetal",
    electronegativity: 2.55,
    electronConfiguration: "[He] 2s2 2p2",
    density: 2.267,
    meltingPoint: 3823,
    boilingPoint: 4300,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 14,
    ypos: 2
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: 14.007,
    category: "nonmetal",
    electronegativity: 3.04,
    electronConfiguration: "[He] 2s2 2p3",
    density: 0.001251,
    meltingPoint: 63.15,
    boilingPoint: 77.36,
    discoveredBy: "Daniel Rutherford",
    discoveryYear: 1772,
    xpos: 15,
    ypos: 2
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: 15.999,
    category: "nonmetal",
    electronegativity: 3.44,
    electronConfiguration: "[He] 2s2 2p4",
    density: 0.001429,
    meltingPoint: 54.36,
    boilingPoint: 90.20,
    discoveredBy: "Carl Wilhelm Scheele",
    discoveryYear: 1771,
    xpos: 16,
    ypos: 2
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: 18.998,
    category: "halogen",
    electronegativity: 3.98,
    electronConfiguration: "[He] 2s2 2p5",
    density: 0.001696,
    meltingPoint: 53.53,
    boilingPoint: 85.03,
    discoveredBy: "André-Marie Ampère",
    discoveryYear: 1810,
    xpos: 17,
    ypos: 2
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    atomicMass: 20.180,
    category: "noble gas",
    electronegativity: null,
    electronConfiguration: "[He] 2s2 2p6",
    density: 0.0008999,
    meltingPoint: 24.56,
    boilingPoint: 27.07,
    discoveredBy: "William Ramsay, Morris Travers",
    discoveryYear: 1898,
    xpos: 18,
    ypos: 2
  },
  
  // Period 3
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: 22.990,
    category: "alkali metal",
    electronegativity: 0.93,
    electronConfiguration: "[Ne] 3s1",
    density: 0.971,
    meltingPoint: 370.87,
    boilingPoint: 1156,
    discoveredBy: "Humphry Davy",
    discoveryYear: 1807,
    xpos: 1,
    ypos: 3
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: 24.305,
    category: "alkaline earth metal",
    electronegativity: 1.31,
    electronConfiguration: "[Ne] 3s2",
    density: 1.738,
    meltingPoint: 923,
    boilingPoint: 1363,
    discoveredBy: "Joseph Black",
    discoveryYear: 1755,
    xpos: 2,
    ypos: 3
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminum",
    atomicMass: 26.982,
    category: "post-transition metal",
    electronegativity: 1.61,
    electronConfiguration: "[Ne] 3s2 3p1",
    density: 2.698,
    meltingPoint: 933.47,
    boilingPoint: 2792,
    discoveredBy: "Hans Christian Ørsted",
    discoveryYear: 1825,
    xpos: 13,
    ypos: 3
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: 28.085,
    category: "metalloid",
    electronegativity: 1.9,
    electronConfiguration: "[Ne] 3s2 3p2",
    density: 2.3296,
    meltingPoint: 1687,
    boilingPoint: 3538,
    discoveredBy: "Jöns Jacob Berzelius",
    discoveryYear: 1824,
    xpos: 14,
    ypos: 3
  },
  {
    atomicNumber: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicMass: 30.974,
    category: "nonmetal",
    electronegativity: 2.19,
    electronConfiguration: "[Ne] 3s2 3p3",
    density: 1.82,
    meltingPoint: 317.3,
    boilingPoint: 550,
    discoveredBy: "Hennig Brand",
    discoveryYear: 1669,
    xpos: 15,
    ypos: 3
  },
  {
    atomicNumber: 16,
    symbol: "S",
    name: "Sulfur",
    atomicMass: 32.06,
    category: "nonmetal",
    electronegativity: 2.58,
    electronConfiguration: "[Ne] 3s2 3p4",
    density: 2.067,
    meltingPoint: 388.36,
    boilingPoint: 717.87,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 16,
    ypos: 3
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: 35.45,
    category: "halogen",
    electronegativity: 3.16,
    electronConfiguration: "[Ne] 3s2 3p5",
    density: 0.003214,
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    discoveredBy: "Carl Wilhelm Scheele",
    discoveryYear: 1774,
    xpos: 17,
    ypos: 3
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    atomicMass: 39.948,
    category: "noble gas",
    electronegativity: null,
    electronConfiguration: "[Ne] 3s2 3p6",
    density: 0.0017837,
    meltingPoint: 83.80,
    boilingPoint: 87.30,
    discoveredBy: "Lord Rayleigh, William Ramsay",
    discoveryYear: 1894,
    xpos: 18,
    ypos: 3
  },
  
  // Period 4
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    atomicMass: 39.098,
    category: "alkali metal",
    electronegativity: 0.82,
    electronConfiguration: "[Ar] 4s1",
    density: 0.862,
    meltingPoint: 336.53,
    boilingPoint: 1032,
    discoveredBy: "Humphry Davy",
    discoveryYear: 1807,
    xpos: 1,
    ypos: 4
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicMass: 40.078,
    category: "alkaline earth metal",
    electronegativity: 1.00,
    electronConfiguration: "[Ar] 4s2",
    density: 1.54,
    meltingPoint: 1115,
    boilingPoint: 1757,
    discoveredBy: "Humphry Davy",
    discoveryYear: 1808,
    xpos: 2,
    ypos: 4
  },
  {
    atomicNumber: 21,
    symbol: "Sc",
    name: "Scandium",
    atomicMass: 44.956,
    category: "transition metal",
    electronegativity: 1.36,
    electronConfiguration: "[Ar] 3d1 4s2",
    density: 2.985,
    meltingPoint: 1814,
    boilingPoint: 3109,
    discoveredBy: "Lars Fredrik Nilson",
    discoveryYear: 1879,
    xpos: 3,
    ypos: 4
  },
  {
    atomicNumber: 22,
    symbol: "Ti",
    name: "Titanium",
    atomicMass: 47.867,
    category: "transition metal",
    electronegativity: 1.54,
    electronConfiguration: "[Ar] 3d2 4s2",
    density: 4.507,
    meltingPoint: 1941,
    boilingPoint: 3560,
    discoveredBy: "William Gregor",
    discoveryYear: 1791,
    xpos: 4,
    ypos: 4
  },
  {
    atomicNumber: 23,
    symbol: "V",
    name: "Vanadium",
    atomicMass: 50.942,
    category: "transition metal",
    electronegativity: 1.63,
    electronConfiguration: "[Ar] 3d3 4s2",
    density: 6.11,
    meltingPoint: 2183,
    boilingPoint: 3680,
    discoveredBy: "Andrés Manuel del Río",
    discoveryYear: 1801,
    xpos: 5,
    ypos: 4
  },
  {
    atomicNumber: 24,
    symbol: "Cr",
    name: "Chromium",
    atomicMass: 51.996,
    category: "transition metal",
    electronegativity: 1.66,
    electronConfiguration: "[Ar] 3d5 4s1",
    density: 7.15,
    meltingPoint: 2180,
    boilingPoint: 2944,
    discoveredBy: "Louis Nicolas Vauquelin",
    discoveryYear: 1794,
    xpos: 6,
    ypos: 4
  },
  {
    atomicNumber: 25,
    symbol: "Mn",
    name: "Manganese",
    atomicMass: 54.938,
    category: "transition metal",
    electronegativity: 1.55,
    electronConfiguration: "[Ar] 3d5 4s2",
    density: 7.21,
    meltingPoint: 1519,
    boilingPoint: 2334,
    discoveredBy: "Johann Gottlieb Gahn",
    discoveryYear: 1774,
    xpos: 7,
    ypos: 4
  },
  {
    atomicNumber: 26,
    symbol: "Fe",
    name: "Iron",
    atomicMass: 55.845,
    category: "transition metal",
    electronegativity: 1.83,
    electronConfiguration: "[Ar] 3d6 4s2",
    density: 7.874,
    meltingPoint: 1811,
    boilingPoint: 3134,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 8,
    ypos: 4
  },
  {
    atomicNumber: 27,
    symbol: "Co",
    name: "Cobalt",
    atomicMass: 58.933,
    category: "transition metal",
    electronegativity: 1.88,
    electronConfiguration: "[Ar] 3d7 4s2",
    density: 8.90,
    meltingPoint: 1768,
    boilingPoint: 3200,
    discoveredBy: "Georg Brandt",
    discoveryYear: 1735,
    xpos: 9,
    ypos: 4
  },
  {
    atomicNumber: 28,
    symbol: "Ni",
    name: "Nickel",
    atomicMass: 58.693,
    category: "transition metal",
    electronegativity: 1.91,
    electronConfiguration: "[Ar] 3d8 4s2",
    density: 8.908,
    meltingPoint: 1728,
    boilingPoint: 3186,
    discoveredBy: "Axel Fredrik Cronstedt",
    discoveryYear: 1751,
    xpos: 10,
    ypos: 4
  },
  {
    atomicNumber: 29,
    symbol: "Cu",
    name: "Copper",
    atomicMass: 63.546,
    category: "transition metal",
    electronegativity: 1.90,
    electronConfiguration: "[Ar] 3d10 4s1",
    density: 8.96,
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 11,
    ypos: 4
  },
  {
    atomicNumber: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicMass: 65.38,
    category: "transition metal",
    electronegativity: 1.65,
    electronConfiguration: "[Ar] 3d10 4s2",
    density: 7.134,
    meltingPoint: 692.68,
    boilingPoint: 1180,
    discoveredBy: "Indian metallurgists",
    discoveryYear: 1000,
    xpos: 12,
    ypos: 4
  },
  {
    atomicNumber: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicMass: 69.723,
    category: "post-transition metal",
    electronegativity: 1.81,
    electronConfiguration: "[Ar] 3d10 4s2 4p1",
    density: 5.91,
    meltingPoint: 302.9146,
    boilingPoint: 2673,
    discoveredBy: "Lecoq de Boisbaudran",
    discoveryYear: 1875,
    xpos: 13,
    ypos: 4
  },
  {
    atomicNumber: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicMass: 72.630,
    category: "metalloid",
    electronegativity: 2.01,
    electronConfiguration: "[Ar] 3d10 4s2 4p2",
    density: 5.323,
    meltingPoint: 1211.40,
    boilingPoint: 3106,
    discoveredBy: "Clemens Winkler",
    discoveryYear: 1886,
    xpos: 14,
    ypos: 4
  },
  {
    atomicNumber: 33,
    symbol: "As",
    name: "Arsenic",
    atomicMass: 74.922,
    category: "metalloid",
    electronegativity: 2.18,
    electronConfiguration: "[Ar] 3d10 4s2 4p3",
    density: 5.727,
    meltingPoint: 1090,
    boilingPoint: 887,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 15,
    ypos: 4
  },
  {
    atomicNumber: 34,
    symbol: "Se",
    name: "Selenium",
    atomicMass: 78.971,
    category: "nonmetal",
    electronegativity: 2.55,
    electronConfiguration: "[Ar] 3d10 4s2 4p4",
    density: 4.81,
    meltingPoint: 494,
    boilingPoint: 958,
    discoveredBy: "Jöns Jacob Berzelius",
    discoveryYear: 1817,
    xpos: 16,
    ypos: 4
  },
  {
    atomicNumber: 35,
    symbol: "Br",
    name: "Bromine",
    atomicMass: 79.904,
    category: "halogen",
    electronegativity: 2.96,
    electronConfiguration: "[Ar] 3d10 4s2 4p5",
    density: 3.1028,
    meltingPoint: 265.8,
    boilingPoint: 332.0,
    discoveredBy: "Antoine Jérôme Balard",
    discoveryYear: 1826,
    xpos: 17,
    ypos: 4
  },
  {
    atomicNumber: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicMass: 83.798,
    category: "noble gas",
    electronegativity: 3.00,
    electronConfiguration: "[Ar] 3d10 4s2 4p6",
    density: 0.003733,
    meltingPoint: 115.79,
    boilingPoint: 119.93,
    discoveredBy: "William Ramsay, Morris Travers",
    discoveryYear: 1898,
    xpos: 18,
    ypos: 4
  },
  
  // Period 5
  {
    atomicNumber: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomicMass: 85.468,
    category: "alkali metal",
    electronegativity: 0.82,
    electronConfiguration: "[Kr] 5s1",
    density: 1.532,
    meltingPoint: 312.46,
    boilingPoint: 961,
    discoveredBy: "Robert Bunsen, Gustav Kirchhoff",
    discoveryYear: 1861,
    xpos: 1,
    ypos: 5
  },
  {
    atomicNumber: 38,
    symbol: "Sr",
    name: "Strontium",
    atomicMass: 87.62,
    category: "alkaline earth metal",
    electronegativity: 0.95,
    electronConfiguration: "[Kr] 5s2",
    density: 2.64,
    meltingPoint: 1050,
    boilingPoint: 1655,
    discoveredBy: "Adair Crawford",
    discoveryYear: 1790,
    xpos: 2,
    ypos: 5
  },
  {
    atomicNumber: 39,
    symbol: "Y",
    name: "Yttrium",
    atomicMass: 88.906,
    category: "transition metal",
    electronegativity: 1.22,
    electronConfiguration: "[Kr] 4d1 5s2",
    density: 4.469,
    meltingPoint: 1799,
    boilingPoint: 3609,
    discoveredBy: "Johan Gadolin",
    discoveryYear: 1794,
    xpos: 3,
    ypos: 5
  },
  {
    atomicNumber: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomicMass: 91.224,
    category: "transition metal",
    electronegativity: 1.33,
    electronConfiguration: "[Kr] 4d2 5s2",
    density: 6.506,
    meltingPoint: 2128,
    boilingPoint: 4682,
    discoveredBy: "Martin Heinrich Klaproth",
    discoveryYear: 1789,
    xpos: 4,
    ypos: 5
  },
  {
    atomicNumber: 41,
    symbol: "Nb",
    name: "Niobium",
    atomicMass: 92.906,
    category: "transition metal",
    electronegativity: 1.6,
    electronConfiguration: "[Kr] 4d4 5s1",
    density: 8.57,
    meltingPoint: 2750,
    boilingPoint: 5017,
    discoveredBy: "Charles Hatchett",
    discoveryYear: 1801,
    xpos: 5,
    ypos: 5
  },
  {
    atomicNumber: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomicMass: 95.95,
    category: "transition metal",
    electronegativity: 2.16,
    electronConfiguration: "[Kr] 4d5 5s1",
    density: 10.22,
    meltingPoint: 2896,
    boilingPoint: 4912,
    discoveredBy: "Carl Wilhelm Scheele",
    discoveryYear: 1778,
    xpos: 6,
    ypos: 5
  },
  {
    atomicNumber: 43,
    symbol: "Tc",
    name: "Technetium",
    atomicMass: 98,
    category: "transition metal",
    electronegativity: 1.9,
    electronConfiguration: "[Kr] 4d5 5s2",
    density: 11.5,
    meltingPoint: 2430,
    boilingPoint: 4538,
    discoveredBy: "Carlo Perrier, Emilio Segrè",
    discoveryYear: 1937,
    xpos: 7,
    ypos: 5
  },
  {
    atomicNumber: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomicMass: 101.07,
    category: "transition metal",
    electronegativity: 2.2,
    electronConfiguration: "[Kr] 4d7 5s1",
    density: 12.37,
    meltingPoint: 2607,
    boilingPoint: 4423,
    discoveredBy: "Karl Ernst Claus",
    discoveryYear: 1844,
    xpos: 8,
    ypos: 5
  },
  {
    atomicNumber: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomicMass: 102.91,
    category: "transition metal",
    electronegativity: 2.28,
    electronConfiguration: "[Kr] 4d8 5s1",
    density: 12.41,
    meltingPoint: 2237,
    boilingPoint: 3968,
    discoveredBy: "William Hyde Wollaston",
    discoveryYear: 1804,
    xpos: 9,
    ypos: 5
  },
  {
    atomicNumber: 46,
    symbol: "Pd",
    name: "Palladium",
    atomicMass: 106.42,
    category: "transition metal",
    electronegativity: 2.2,
    electronConfiguration: "[Kr] 4d10",
    density: 12.02,
    meltingPoint: 1828.05,
    boilingPoint: 3236,
    discoveredBy: "William Hyde Wollaston",
    discoveryYear: 1803,
    xpos: 10,
    ypos: 5
  },
  {
    atomicNumber: 47,
    symbol: "Ag",
    name: "Silver",
    atomicMass: 107.87,
    category: "transition metal",
    electronegativity: 1.93,
    electronConfiguration: "[Kr] 4d10 5s1",
    density: 10.49,
    meltingPoint: 1234.93,
    boilingPoint: 2435,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 11,
    ypos: 5
  },
  {
    atomicNumber: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomicMass: 112.41,
    category: "transition metal",
    electronegativity: 1.69,
    electronConfiguration: "[Kr] 4d10 5s2",
    density: 8.65,
    meltingPoint: 594.22,
    boilingPoint: 1040,
    discoveredBy: "Karl Samuel Leberecht Hermann, Friedrich Stromeyer",
    discoveryYear: 1817,
    xpos: 12,
    ypos: 5
  },
  {
    atomicNumber: 49,
    symbol: "In",
    name: "Indium",
    atomicMass: 114.82,
    category: "post-transition metal",
    electronegativity: 1.78,
    electronConfiguration: "[Kr] 4d10 5s2 5p1",
    density: 7.31,
    meltingPoint: 429.75,
    boilingPoint: 2345,
    discoveredBy: "Ferdinand Reich, Hieronymous Theodor Richter",
    discoveryYear: 1863,
    xpos: 13,
    ypos: 5
  },
  {
    atomicNumber: 50,
    symbol: "Sn",
    name: "Tin",
    atomicMass: 118.71,
    category: "post-transition metal",
    electronegativity: 1.96,
    electronConfiguration: "[Kr] 4d10 5s2 5p2",
    density: 7.287,
    meltingPoint: 505.08,
    boilingPoint: 2875,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 14,
    ypos: 5
  },
  {
    atomicNumber: 51,
    symbol: "Sb",
    name: "Antimony",
    atomicMass: 121.76,
    category: "metalloid",
    electronegativity: 2.05,
    electronConfiguration: "[Kr] 4d10 5s2 5p3",
    density: 6.685,
    meltingPoint: 903.78,
    boilingPoint: 1860,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 15,
    ypos: 5
  },
  {
    atomicNumber: 52,
    symbol: "Te",
    name: "Tellurium",
    atomicMass: 127.6,
    category: "metalloid",
    electronegativity: 2.1,
    electronConfiguration: "[Kr] 4d10 5s2 5p4",
    density: 6.232,
    meltingPoint: 722.66,
    boilingPoint: 1261,
    discoveredBy: "Franz Joseph Müller von Reichenstein",
    discoveryYear: 1782,
    xpos: 16,
    ypos: 5
  },
  {
    atomicNumber: 53,
    symbol: "I",
    name: "Iodine",
    atomicMass: 126.9,
    category: "halogen",
    electronegativity: 2.66,
    electronConfiguration: "[Kr] 4d10 5s2 5p5",
    density: 4.93,
    meltingPoint: 386.85,
    boilingPoint: 457.4,
    discoveredBy: "Bernard Courtois",
    discoveryYear: 1811,
    xpos: 17,
    ypos: 5
  },
  {
    atomicNumber: 54,
    symbol: "Xe",
    name: "Xenon",
    atomicMass: 131.29,
    category: "noble gas",
    electronegativity: 2.6,
    electronConfiguration: "[Kr] 4d10 5s2 5p6",
    density: 0.005887,
    meltingPoint: 161.4,
    boilingPoint: 165.03,
    discoveredBy: "William Ramsay, Morris Travers",
    discoveryYear: 1898,
    xpos: 18,
    ypos: 5
  },
  
  // Period 6
  {
    atomicNumber: 55,
    symbol: "Cs",
    name: "Cesium",
    atomicMass: 132.91,
    category: "alkali metal",
    electronegativity: 0.79,
    electronConfiguration: "[Xe] 6s1",
    density: 1.873,
    meltingPoint: 301.59,
    boilingPoint: 944,
    discoveredBy: "Robert Bunsen, Gustav Kirchhoff",
    discoveryYear: 1860,
    xpos: 1,
    ypos: 6
  },
  {
    atomicNumber: 56,
    symbol: "Ba",
    name: "Barium",
    atomicMass: 137.33,
    category: "alkaline earth metal",
    electronegativity: 0.89,
    electronConfiguration: "[Xe] 6s2",
    density: 3.594,
    meltingPoint: 1000,
    boilingPoint: 2170,
    discoveredBy: "Carl Wilhelm Scheele",
    discoveryYear: 1772,
    xpos: 2,
    ypos: 6
  },
  {
    atomicNumber: 57,
    symbol: "La",
    name: "Lanthanum",
    atomicMass: 138.91,
    category: "lanthanide",
    electronegativity: 1.1,
    electronConfiguration: "[Xe] 5d1 6s2",
    density: 6.145,
    meltingPoint: 1193,
    boilingPoint: 3737,
    discoveredBy: "Carl Gustaf Mosander",
    discoveryYear: 1839,
    xpos: 3,
    ypos: 6
  },
  {
    atomicNumber: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomicMass: 178.49,
    category: "transition metal",
    electronegativity: 1.3,
    electronConfiguration: "[Xe] 4f14 5d2 6s2",
    density: 13.31,
    meltingPoint: 2506,
    boilingPoint: 4876,
    discoveredBy: "Dirk Coster, George de Hevesy",
    discoveryYear: 1923,
    xpos: 4,
    ypos: 6
  },
  {
    atomicNumber: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomicMass: 180.95,
    category: "transition metal",
    electronegativity: 1.5,
    electronConfiguration: "[Xe] 4f14 5d3 6s2",
    density: 16.654,
    meltingPoint: 3290,
    boilingPoint: 5731,
    discoveredBy: "Anders Gustaf Ekeberg",
    discoveryYear: 1802,
    xpos: 5,
    ypos: 6
  },
  {
    atomicNumber: 74,
    symbol: "W",
    name: "Tungsten",
    atomicMass: 183.84,
    category: "transition metal",
    electronegativity: 2.36,
    electronConfiguration: "[Xe] 4f14 5d4 6s2",
    density: 19.25,
    meltingPoint: 3695,
    boilingPoint: 5828,
    discoveredBy: "Carl Wilhelm Scheele",
    discoveryYear: 1781,
    xpos: 6,
    ypos: 6
  },
  {
    atomicNumber: 75,
    symbol: "Re",
    name: "Rhenium",
    atomicMass: 186.21,
    category: "transition metal",
    electronegativity: 1.9,
    electronConfiguration: "[Xe] 4f14 5d5 6s2",
    density: 21.02,
    meltingPoint: 3459,
    boilingPoint: 5869,
    discoveredBy: "Masataka Ogawa",
    discoveryYear: 1908,
    xpos: 7,
    ypos: 6
  },
  {
    atomicNumber: 76,
    symbol: "Os",
    name: "Osmium",
    atomicMass: 190.23,
    category: "transition metal",
    electronegativity: 2.2,
    electronConfiguration: "[Xe] 4f14 5d6 6s2",
    density: 22.59,
    meltingPoint: 3306,
    boilingPoint: 5285,
    discoveredBy: "Smithson Tennant",
    discoveryYear: 1803,
    xpos: 8,
    ypos: 6
  },
  {
    atomicNumber: 77,
    symbol: "Ir",
    name: "Iridium",
    atomicMass: 192.22,
    category: "transition metal",
    electronegativity: 2.2,
    electronConfiguration: "[Xe] 4f14 5d7 6s2",
    density: 22.56,
    meltingPoint: 2719,
    boilingPoint: 4701,
    discoveredBy: "Smithson Tennant",
    discoveryYear: 1803,
    xpos: 9,
    ypos: 6
  },
  {
    atomicNumber: 78,
    symbol: "Pt",
    name: "Platinum",
    atomicMass: 195.08,
    category: "transition metal",
    electronegativity: 2.28,
    electronConfiguration: "[Xe] 4f14 5d9 6s1",
    density: 21.45,
    meltingPoint: 2041.4,
    boilingPoint: 4098,
    discoveredBy: "Antonio de Ulloa",
    discoveryYear: 1735,
    xpos: 10,
    ypos: 6
  },
  {
    atomicNumber: 79,
    symbol: "Au",
    name: "Gold",
    atomicMass: 196.97,
    category: "transition metal",
    electronegativity: 2.54,
    electronConfiguration: "[Xe] 4f14 5d10 6s1",
    density: 19.3,
    meltingPoint: 1337.33,
    boilingPoint: 3129,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 11,
    ypos: 6
  },
  {
    atomicNumber: 80,
    symbol: "Hg",
    name: "Mercury",
    atomicMass: 200.59,
    category: "transition metal",
    electronegativity: 2.0,
    electronConfiguration: "[Xe] 4f14 5d10 6s2",
    density: 13.546,
    meltingPoint: 234.43,
    boilingPoint: 629.88,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 12,
    ypos: 6
  },
  {
    atomicNumber: 81,
    symbol: "Tl",
    name: "Thallium",
    atomicMass: 204.38,
    category: "post-transition metal",
    electronegativity: 1.62,
    electronConfiguration: "[Xe] 4f14 5d10 6s2 6p1",
    density: 11.85,
    meltingPoint: 577,
    boilingPoint: 1746,
    discoveredBy: "William Crookes",
    discoveryYear: 1861,
    xpos: 13,
    ypos: 6
  },
  {
    atomicNumber: 82,
    symbol: "Pb",
    name: "Lead",
    atomicMass: 207.2,
    category: "post-transition metal",
    electronegativity: 2.33,
    electronConfiguration: "[Xe] 4f14 5d10 6s2 6p2",
    density: 11.34,
    meltingPoint: 600.61,
    boilingPoint: 2022,
    discoveredBy: "Ancient",
    discoveryYear: null,
    xpos: 14,
    ypos: 6
  },
  {
    atomicNumber: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomicMass: 208.98,
    category: "post-transition metal",
    electronegativity: 2.02,
    electronConfiguration: "[Xe] 4f14 5d10 6s2 6p3",
    density: 9.78,
    meltingPoint: 544.7,
    boilingPoint: 1837,
    discoveredBy: "Claude François Geoffroy",
    discoveryYear: 1753,
    xpos: 15,
    ypos: 6
  },
  {
    atomicNumber: 84,
    symbol: "Po",
    name: "Polonium",
    atomicMass: 209,
    category: "post-transition metal",
    electronegativity: 2.0,
    electronConfiguration: "[Xe] 4f14 5d10 6s2 6p4",
    density: 9.196,
    meltingPoint: 527,
    boilingPoint: 1235,
    discoveredBy: "Pierre Curie, Marie Curie",
    discoveryYear: 1898,
    xpos: 16,
    ypos: 6
  },
  {
    atomicNumber: 85,
    symbol: "At",
    name: "Astatine",
    atomicMass: 210,
    category: "halogen",
    electronegativity: 2.2,
    electronConfiguration: "[Xe] 4f14 5d10 6s2 6p5",
    density: 7,
    meltingPoint: 575,
    boilingPoint: 610,
    discoveredBy: "Dale R. Corson, Kenneth Ross MacKenzie, Emilio Segrè",
    discoveryYear: 1940,
    xpos: 17,
    ypos: 6
  },
  {
    atomicNumber: 86,
    symbol: "Rn",
    name: "Radon",
    atomicMass: 222,
    category: "noble gas",
    electronegativity: 2.2,
    electronConfiguration: "[Xe] 4f14 5d10 6s2 6p6",
    density: 0.00973,
    meltingPoint: 202,
    boilingPoint: 211.3,
    discoveredBy: "Friedrich Ernst Dorn",
    discoveryYear: 1900,
    xpos: 18,
    ypos: 6
  },
  
  // Period 7
  {
    atomicNumber: 87,
    symbol: "Fr",
    name: "Francium",
    atomicMass: 223,
    category: "alkali metal",
    electronegativity: 0.7,
    electronConfiguration: "[Rn] 7s1",
    density: 1.87,
    meltingPoint: 300,
    boilingPoint: 950,
    discoveredBy: "Marguerite Perey",
    discoveryYear: 1939,
    xpos: 1,
    ypos: 7
  },
  {
    atomicNumber: 88,
    symbol: "Ra",
    name: "Radium",
    atomicMass: 226,
    category: "alkaline earth metal",
    electronegativity: 0.9,
    electronConfiguration: "[Rn] 7s2",
    density: 5.5,
    meltingPoint: 973,
    boilingPoint: 2010,
    discoveredBy: "Pierre Curie, Marie Curie",
    discoveryYear: 1898,
    xpos: 2,
    ypos: 7
  },
  {
    atomicNumber: 89,
    symbol: "Ac",
    name: "Actinium",
    atomicMass: 227,
    category: "actinide",
    electronegativity: 1.1,
    electronConfiguration: "[Rn] 6d1 7s2",
    density: 10.07,
    meltingPoint: 1323,
    boilingPoint: 3471,
    discoveredBy: "Friedrich Oskar Giesel",
    discoveryYear: 1902,
    xpos: 3,
    ypos: 7
  },
  {
    atomicNumber: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomicMass: 267,
    category: "transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d2 7s2",
    density: 23,
    meltingPoint: 2400,
    boilingPoint: 5800,
    discoveredBy: "Joint Institute for Nuclear Research",
    discoveryYear: 1964,
    xpos: 4,
    ypos: 7
  },
  {
    atomicNumber: 105,
    symbol: "Db",
    name: "Dubnium",
    atomicMass: 268,
    category: "transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d3 7s2",
    density: 29.3,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Joint Institute for Nuclear Research",
    discoveryYear: 1967,
    xpos: 5,
    ypos: 7
  },
  {
    atomicNumber: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomicMass: 269,
    category: "transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d4 7s2",
    density: 35.0,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Lawrence Berkeley Laboratory",
    discoveryYear: 1974,
    xpos: 6,
    ypos: 7
  },
  {
    atomicNumber: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomicMass: 270,
    category: "transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d5 7s2",
    density: 37.1,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Gesellschaft für Schwerionenforschung",
    discoveryYear: 1981,
    xpos: 7,
    ypos: 7
  },
  {
    atomicNumber: 108,
    symbol: "Hs",
    name: "Hassium",
    atomicMass: 277,
    category: "transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d6 7s2",
    density: 40.7,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Gesellschaft für Schwerionenforschung",
    discoveryYear: 1984,
    xpos: 8,
    ypos: 7
  },
  {
    atomicNumber: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomicMass: 278,
    category: "transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d7 7s2",
    density: 37.4,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Gesellschaft für Schwerionenforschung",
    discoveryYear: 1982,
    xpos: 9,
    ypos: 7
  },
  {
    atomicNumber: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomicMass: 281,
    category: "transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d8 7s2",
    density: 34.8,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Gesellschaft für Schwerionenforschung",
    discoveryYear: 1994,
    xpos: 10,
    ypos: 7
  },
  {
    atomicNumber: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomicMass: 282,
    category: "transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d9 7s2",
    density: 28.7,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Gesellschaft für Schwerionenforschung",
    discoveryYear: 1994,
    xpos: 11,
    ypos: 7
  },
  {
    atomicNumber: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomicMass: 285,
    category: "transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d10 7s2",
    density: 23.7,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Gesellschaft für Schwerionenforschung",
    discoveryYear: 1996,
    xpos: 12,
    ypos: 7
  },
  {
    atomicNumber: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomicMass: 286,
    category: "post-transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d10 7s2 7p1",
    density: 16,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "RIKEN",
    discoveryYear: 2004,
    xpos: 13,
    ypos: 7
  },
  {
    atomicNumber: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomicMass: 289,
    category: "post-transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d10 7s2 7p2",
    density: 14,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Joint Institute for Nuclear Research",
    discoveryYear: 1998,
    xpos: 14,
    ypos: 7
  },
  {
    atomicNumber: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomicMass: 290,
    category: "post-transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d10 7s2 7p3",
    density: 13.5,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Joint Institute for Nuclear Research",
    discoveryYear: 2003,
    xpos: 15,
    ypos: 7
  },
  {
    atomicNumber: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomicMass: 293,
    category: "post-transition metal",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d10 7s2 7p4",
    density: 12.9,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Joint Institute for Nuclear Research",
    discoveryYear: 2000,
    xpos: 16,
    ypos: 7
  },
  {
    atomicNumber: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomicMass: 294,
    category: "halogen",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d10 7s2 7p5",
    density: 7.2,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Joint Institute for Nuclear Research",
    discoveryYear: 2010,
    xpos: 17,
    ypos: 7
  },
  {
    atomicNumber: 118,
    symbol: "Og",
    name: "Oganesson",
    atomicMass: 294,
    category: "noble gas",
    electronegativity: null,
    electronConfiguration: "[Rn] 5f14 6d10 7s2 7p6",
    density: 5,
    meltingPoint: null,
    boilingPoint: null,
    discoveredBy: "Joint Institute for Nuclear Research",
    discoveryYear: 2002,
    xpos: 18,
    ypos: 7
  },
  
  // Lanthanides (Period 6, Group 3)
  {
    atomicNumber: 58,
    symbol: "Ce",
    name: "Cerium",
    atomicMass: 140.12,
    category: "lanthanide",
    electronegativity: 1.12,
    electronConfiguration: "[Xe] 4f1 5d1 6s2",
    density: 6.770,
    meltingPoint: 1068,
    boilingPoint: 3716,
    discoveredBy: "Martin Heinrich Klaproth, Jöns Jakob Berzelius, Wilhelm Hisinger",
    discoveryYear: 1803,
    xpos: 4,
    ypos: 9
  },
  {
    atomicNumber: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomicMass: 140.91,
    category: "lanthanide",
    electronegativity: 1.13,
    electronConfiguration: "[Xe] 4f3 6s2",
    density: 6.77,
    meltingPoint: 1208,
    boilingPoint: 3793,
    discoveredBy: "Carl Auer von Welsbach",
    discoveryYear: 1885,
    xpos: 5,
    ypos: 9
  },
  {
    atomicNumber: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomicMass: 144.24,
    category: "lanthanide",
    electronegativity: 1.14,
    electronConfiguration: "[Xe] 4f4 6s2",
    density: 7.01,
    meltingPoint: 1297,
    boilingPoint: 3347,
    discoveredBy: "Carl Auer von Welsbach",
    discoveryYear: 1885,
    xpos: 6,
    ypos: 9
  },
  {
    atomicNumber: 61,
    symbol: "Pm",
    name: "Promethium",
    atomicMass: 145,
    category: "lanthanide",
    electronegativity: 1.13,
    electronConfiguration: "[Xe] 4f5 6s2",
    density: 7.26,
    meltingPoint: 1315,
    boilingPoint: 3273,
    discoveredBy: "Chien Shiung Wu, Emilio Segrè, Hans Bethe",
    discoveryYear: 1945,
    xpos: 7,
    ypos: 9
  },
  {
    atomicNumber: 62,
    symbol: "Sm",
    name: "Samarium",
    atomicMass: 150.36,
    category: "lanthanide",
    electronegativity: 1.17,
    electronConfiguration: "[Xe] 4f6 6s2",
    density: 7.52,
    meltingPoint: 1345,
    boilingPoint: 2067,
    discoveredBy: "Paul Émile Lecoq de Boisbaudran",
    discoveryYear: 1879,
    xpos: 8,
    ypos: 9
  },
  {
    atomicNumber: 63,
    symbol: "Eu",
    name: "Europium",
    atomicMass: 151.96,
    category: "lanthanide",
    electronegativity: 1.2,
    electronConfiguration: "[Xe] 4f7 6s2",
    density: 5.264,
    meltingPoint: 1099,
    boilingPoint: 1802,
    discoveredBy: "Eugène-Anatole Demarçay",
    discoveryYear: 1901,
    xpos: 9,
    ypos: 9
  },
  {
    atomicNumber: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomicMass: 157.25,
    category: "lanthanide",
    electronegativity: 1.2,
    electronConfiguration: "[Xe] 4f7 5d1 6s2",
    density: 7.90,
    meltingPoint: 1585,
    boilingPoint: 3546,
    discoveredBy: "Jean Charles Galissard de Marignac",
    discoveryYear: 1880,
    xpos: 10,
    ypos: 9
  },
  {
    atomicNumber: 65,
    symbol: "Tb",
    name: "Terbium",
    atomicMass: 158.93,
    category: "lanthanide",
    electronegativity: 1.2,
    electronConfiguration: "[Xe] 4f9 6s2",
    density: 8.23,
    meltingPoint: 1629,
    boilingPoint: 3503,
    discoveredBy: "Carl Gustaf Mosander",
    discoveryYear: 1843,
    xpos: 11,
    ypos: 9
  },
  {
    atomicNumber: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomicMass: 162.50,
    category: "lanthanide",
    electronegativity: 1.22,
    electronConfiguration: "[Xe] 4f10 6s2",
    density: 8.540,
    meltingPoint: 1680,
    boilingPoint: 2840,
    discoveredBy: "Paul Émile Lecoq de Boisbaudran",
    discoveryYear: 1886,
    xpos: 12,
    ypos: 9
  },
  {
    atomicNumber: 67,
    symbol: "Ho",
    name: "Holmium",
    atomicMass: 164.93,
    category: "lanthanide",
    electronegativity: 1.23,
    electronConfiguration: "[Xe] 4f11 6s2",
    density: 8.79,
    meltingPoint: 1734,
    boilingPoint: 2993,
    discoveredBy: "Marc Delafontaine, Jacques-Louis Soret",
    discoveryYear: 1878,
    xpos: 13,
    ypos: 9
  },
  {
    atomicNumber: 68,
    symbol: "Er",
    name: "Erbium",
    atomicMass: 167.26,
    category: "lanthanide",
    electronegativity: 1.24,
    electronConfiguration: "[Xe] 4f12 6s2",
    density: 9.066,
    meltingPoint: 1802,
    boilingPoint: 3141,
    discoveredBy: "Carl Gustaf Mosander",
    discoveryYear: 1843,
    xpos: 14,
    ypos: 9
  },
  {
    atomicNumber: 69,
    symbol: "Tm",
    name: "Thulium",
    atomicMass: 168.93,
    category: "lanthanide",
    electronegativity: 1.25,
    electronConfiguration: "[Xe] 4f13 6s2",
    density: 9.32,
    meltingPoint: 1818,
    boilingPoint: 2223,
    discoveredBy: "Per Teodor Cleve",
    discoveryYear: 1879,
    xpos: 15,
    ypos: 9
  },
  {
    atomicNumber: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomicMass: 173.05,
    category: "lanthanide",
    electronegativity: 1.1,
    electronConfiguration: "[Xe] 4f14 6s2",
    density: 6.90,
    meltingPoint: 1097,
    boilingPoint: 1469,
    discoveredBy: "Jean Charles Galissard de Marignac",
    discoveryYear: 1878,
    xpos: 16,
    ypos: 9
  },
  {
    atomicNumber: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomicMass: 174.97,
    category: "lanthanide",
    electronegativity: 1.27,
    electronConfiguration: "[Xe] 4f14 5d1 6s2",
    density: 9.841,
    meltingPoint: 1925,
    boilingPoint: 3675,
    discoveredBy: "Georges Urbain, Carl Auer von Welsbach",
    discoveryYear: 1907,
    xpos: 17,
    ypos: 9
  },
  
  // Actinides (Period 7, Group 3)
  {
    atomicNumber: 90,
    symbol: "Th",
    name: "Thorium",
    atomicMass: 232.04,
    category: "actinide",
    electronegativity: 1.3,
    electronConfiguration: "[Rn] 6d2 7s2",
    density: 11.72,
    meltingPoint: 2115,
    boilingPoint: 5061,
    discoveredBy: "Jöns Jakob Berzelius",
    discoveryYear: 1829,
    xpos: 4,
    ypos: 10
  },
  {
    atomicNumber: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomicMass: 231.04,
    category: "actinide",
    electronegativity: 1.5,
    electronConfiguration: "[Rn] 5f2 6d1 7s2",
    density: 15.37,
    meltingPoint: 1841,
    boilingPoint: 4300,
    discoveredBy: "William Crookes",
    discoveryYear: 1913,
    xpos: 5,
    ypos: 10
  },
  {
    atomicNumber: 92,
    symbol: "U",
    name: "Uranium",
    atomicMass: 238.03,
    category: "actinide",
    electronegativity: 1.38,
    electronConfiguration: "[Rn] 5f3 6d1 7s2",
    density: 19.1,
    meltingPoint: 1405.3,
    boilingPoint: 4404,
    discoveredBy: "Martin Heinrich Klaproth",
    discoveryYear: 1789,
    xpos: 6,
    ypos: 10
  },
  {
    atomicNumber: 93,
    symbol: "Np",
    name: "Neptunium",
    atomicMass: 237,
    category: "actinide",
    electronegativity: 1.36,
    electronConfiguration: "[Rn] 5f4 6d1 7s2",
    density: 20.45,
    meltingPoint: 917,
    boilingPoint: 4273,
    discoveredBy: "Edwin McMillan, Philip Abelson",
    discoveryYear: 1940,
    xpos: 7,
    ypos: 10
  },
  {
    atomicNumber: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomicMass: 244,
    category: "actinide",
    electronegativity: 1.28,
    electronConfiguration: "[Rn] 5f6 7s2",
    density: 19.816,
    meltingPoint: 912.5,
    boilingPoint: 3501,
    discoveredBy: "Glenn T. Seaborg, Arthur C. Wahl, Joseph W. Kennedy, Edwin McMillan",
    discoveryYear: 1940,
    xpos: 8,
    ypos: 10
  },
  {
    atomicNumber: 95,
    symbol: "Am",
    name: "Americium",
    atomicMass: 243,
    category: "actinide",
    electronegativity: 1.3,
    electronConfiguration: "[Rn] 5f7 7s2",
    density: 13.69,
    meltingPoint: 1449,
    boilingPoint: 2880,
    discoveredBy: "Glenn T. Seaborg, Ralph A. James, Leon O. Morgan, Albert Ghiorso",
    discoveryYear: 1944,
    xpos: 9,
    ypos: 10
  },
  {
    atomicNumber: 96,
    symbol: "Cm",
    name: "Curium",
    atomicMass: 247,
    category: "actinide",
    electronegativity: 1.3,
    electronConfiguration: "[Rn] 5f7 6d1 7s2",
    density: 13.51,
    meltingPoint: 1613,
    boilingPoint: 3383,
    discoveredBy: "Glenn T. Seaborg, Ralph A. James, Albert Ghiorso",
    discoveryYear: 1944,
    xpos: 10,
    ypos: 10
  },
  {
    atomicNumber: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomicMass: 247,
    category: "actinide",
    electronegativity: 1.3,
    electronConfiguration: "[Rn] 5f9 7s2",
    density: 14.79,
    meltingPoint: 1259,
    boilingPoint: 2900,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    discoveryYear: 1949,
    xpos: 11,
    ypos: 10
  },
  {
    atomicNumber: 98,
    symbol: "Cf",
    name: "Californium",
    atomicMass: 251,
    category: "actinide",
    electronegativity: 1.3,
    electronConfiguration: "[Rn] 5f10 7s2",
    density: 15.1,
    meltingPoint: 1173,
    boilingPoint: 1743,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    discoveryYear: 1950,
    xpos: 12,
    ypos: 10
  },
  {
    atomicNumber: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomicMass: 252,
    category: "actinide",
    electronegativity: 1.3,
    electronConfiguration: "[Rn] 5f11 7s2",
    density: 8.84,
    meltingPoint: 1133,
    boilingPoint: 1269,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    discoveryYear: 1952,
    xpos: 13,
    ypos: 10
  },
  {
    atomicNumber: 100,
    symbol: "Fm",
    name: "Fermium",
    atomicMass: 257,
    category: "actinide",
    electronegativity: 1.3,
    electronConfiguration: "[Rn] 5f12 7s2",
    density: null,
    meltingPoint: 1800,
    boilingPoint: null,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    discoveryYear: 1952,
    xpos: 14,
    ypos: 10
  },
  {
    atomicNumber: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomicMass: 258,
    category: "actinide",
    electronegativity: 1.3,
    electronConfiguration: "[Rn] 5f13 7s2",
    density: null,
    meltingPoint: 1100,
    boilingPoint: null,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    discoveryYear: 1955,
    xpos: 15,
    ypos: 10
  },
  {
    atomicNumber: 102,
    symbol: "No",
    name: "Nobelium",
    atomicMass: 259,
    category: "actinide",
    electronegativity: 1.3,
    electronConfiguration: "[Rn] 5f14 7s2",
    density: null,
    meltingPoint: 1100,
    boilingPoint: null,
    discoveredBy: "Joint Institute for Nuclear Research",
    discoveryYear: 1966,
    xpos: 16,
    ypos: 10
  },
  {
    atomicNumber: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomicMass: 266,
    category: "actinide",
    electronegativity: 1.3,
    electronConfiguration: "[Rn] 5f14 7s2 7p1",
    density: null,
    meltingPoint: 1900,
    boilingPoint: null,
    discoveredBy: "Lawrence Berkeley National Laboratory",
    discoveryYear: 1961,
    xpos: 17,
    ypos: 10
  }
];